name: disposito
description: Semi-automatic dispose holder that allows centralised disposal of objects
version: 0.2.0
repository: https://github.com/arxdeus/disposito

environment:
  sdk: ^3.5.0

dependencies:
  meta: ^1.15.0

dev_dependencies:
  fake_async: ^1.3.3
  logging: ^1.3.0
  test: ^1.24.0
  vm_service: ^15.0.0

