name: Release to pub.dev
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Get Flutter SDK version constraints and packages
        id: matrix
        uses: arxdeus/github_workflows/actions/dart_parse_versions@main
        with:
          parse-lower-version: false
          parse-upper-version: true
  publish:
    name: "Publish"
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: "Setup Dart ${{ matrix.dart-version }}"
      uses: dart-lang/setup-dart@v1
      with:
        sdk: ${{ matrix.dart-version }}

    - name: "Run Dry Publish"
      shell: bash
      id: dry-publish
      run: dart pub publish --dry-run

    - name: "Setup OIDC token"
      uses: dart-lang/setup-dart@v1

    - name: "Run Publish"
      shell: bash
      run: dart pub publish --force
